# Welcome to Jekyll!
# Theme Settings
minimal_mistakes_skin: "default"

# Site Settings
locale: "zh-CN"
title: "郎梓璇的作品集"
title_separator: "-"
name: "郎梓璇"
description: "新媒体技术专业毕业生 - 个人作品展示"
url: "https://ohhacat.github.io"
baseurl: ""
repository: "ohhacat/ohhacat.github.io"
teaser: # /assets/images/500x300.png

# Site Author
author:
  name: "郎梓璇"
  avatar: "/assets/images/me.jpg"
  bio: "正在寻找心仪工作的新媒体技术专业毕业生"
  location: "杭州"
  email: "lang0388@163.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-square-envelope"
      url: "mailto:lang0388@163.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ohhacat"
    - label: "下载我的简历"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/resume.pdf"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# 下面这些是保持系统运行的配置，不用动
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: /page:num/
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - vendor
  - node_modules
  - package.json
  - Gemfile
  - README
